spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
    h2:
    console:
      enabled: true
    profiles:
      include: oauth

server:
  servlet:
    encoding:
      charset: UTF-8
      force-response: true